base:
  group:
    prefix: com
    suffix: dm
  path:
    root-path: C:\Users\duyanhan\Desktop\duyanhan-damiwang
  db:
    ip: 192.168.1.3
    port: 3306
    user: root
    password: 123456

micro-services-module-generator-properties:
  template-file-path: ${base.path.root-path}\micro-service-code-generator\src\main\resources\templateFile
  # 通用模块(common)包含以下子模块，这个通用模块会关联到各个数据库
  common:
    # module模块，用于存放数据库记录对应的实体类(entity，注意不是model)
    module:
      entity-package-name: com.${base.group.suffix}.entity
      entity-save-path: ${base.path.root-path}\${base.group.suffix}-common\${base.group.suffix}-common-module\src\main\java\${base.group.prefix}\${base.group.suffix}\entity
    # dao模块，用于存放数据库对应的数据访问接口和SQL实现的XML文件
    dao:
      mapper-package-name: com.${base.group.suffix}.mapper
      mapper-interface-save-path: ${base.path.root-path}\${base.group.suffix}-common\${base.group.suffix}-common-dao\src\main\java\${base.group.prefix}\${base.group.suffix}\mapper
      mapperXMLSavePath: ${base.path.root-path}\${base.group.suffix}-common\${base.group.suffix}-common-dao\src\main\resources\mapper
    # client模块，用于存放封装了数据访问接口的远程调用接口（简单来讲，就是单体项目中的Service接口）
    client:
      client-package-name: com.${base.group.suffix}.client
      client-save-path: ${base.path.root-path}\${base.group.suffix}-common\${base.group.suffix}-common-client\src\main\java\${base.group.prefix}\${base.group.suffix}\client
      client-fallBack-package-name: com.${base.group.suffix}.fallback
      client-fallBack-save-path: ${base.path.root-path}\${base.group.suffix}-common\${base.group.suffix}-common-client\src\main\java\${base.group.prefix}\${base.group.suffix}\fallback
      client-config-package-name: com.${base.group.suffix}.config
      client-config-save-path: ${base.path.root-path}\${base.group.suffix}-common\${base.group.suffix}-common-client\src\main\java\${base.group.prefix}\${base.group.suffix}\config

  # 具体的业务模块，业务模块各自关联自己需要的数据库
  businesses:
    - business-name: base
      database:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://${base.db.ip}:${base.db.port}/${base.group.suffix}_${micro-services-module-generator-properties.businesses[0].business-name}?useUnicode=true&characterEncoding=utf-8
        user: ${base.db.user}
        password: ${base.db.password}
      # provider模块，用于存放封装了数据访问接口的远程调用接口的具体实现（简单来讲，就是单体项目中的ServiceImpl类）
      provider:
        module-name: ${base.group.suffix}-${micro-services-module-generator-properties.businesses[0].business-name}-provider
        service-implements-package-name: com.${base.group.suffix}.service
        service-implements-save-path: ${base.path.root-path}\${base.group.suffix}-${micro-services-module-generator-properties.businesses[0].business-name}-provider\src\main\java\${base.group.prefix}\${base.group.suffix}\service

    - business-name: item
      database:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://${base.db.ip}:${base.db.port}/${base.group.suffix}_${micro-services-module-generator-properties.businesses[1].business-name}?useUnicode=true&characterEncoding=utf-8
        user: ${base.db.user}
        password: ${base.db.password}
      provider:
        module-name: ${base.group.suffix}-${micro-services-module-generator-properties.businesses[1].business-name}-provider
        service-implements-package-name: com.${base.group.suffix}.service
        service-implements-save-path: ${base.path.root-path}\${base.group.suffix}-${micro-services-module-generator-properties.businesses[1].business-name}-provider\src\main\java\${base.group.prefix}\${base.group.suffix}\service

    - business-name: order
      database:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://${base.db.ip}:${base.db.port}/${base.group.suffix}_${micro-services-module-generator-properties.businesses[2].business-name}?useUnicode=true&characterEncoding=utf-8
        user: ${base.db.user}
        password: ${base.db.password}
      provider:
        module-name: ${base.group.suffix}-${micro-services-module-generator-properties.businesses[2].business-name}-provider
        service-implements-package-name: com.${base.group.suffix}.service
        service-implements-save-path: ${base.path.root-path}\${base.group.suffix}-${micro-services-module-generator-properties.businesses[2].business-name}-provider\src\main\java\${base.group.prefix}\${base.group.suffix}\service

    - business-name: pay
      database:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://${base.db.ip}:${base.db.port}/${base.group.suffix}_${micro-services-module-generator-properties.businesses[3].business-name}?useUnicode=true&characterEncoding=utf-8
        user: ${base.db.user}
        password: ${base.db.password}
      provider:
        module-name: ${base.group.suffix}-${micro-services-module-generator-properties.businesses[3].business-name}-provider
        service-implements-package-name: com.${base.group.suffix}.service
        service-implements-save-path: ${base.path.root-path}\${base.group.suffix}-${micro-services-module-generator-properties.businesses[3].business-name}-provider\src\main\java\${base.group.prefix}\${base.group.suffix}\service

    - business-name: scheduler
      database:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://${base.db.ip}:${base.db.port}/${base.group.suffix}_${micro-services-module-generator-properties.businesses[4].business-name}?useUnicode=true&characterEncoding=utf-8
        user: ${base.db.user}
        password: ${base.db.password}
      provider:
        module-name: ${base.group.suffix}-${micro-services-module-generator-properties.businesses[4].business-name}-provider
        service-implements-package-name: com.${base.group.suffix}.service
        service-implements-save-path: ${base.path.root-path}\${base.group.suffix}-${micro-services-module-generator-properties.businesses[4].business-name}-provider\src\main\java\${base.group.prefix}\${base.group.suffix}\service

    - business-name: user
      database:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://${base.db.ip}:${base.db.port}/${base.group.suffix}_${micro-services-module-generator-properties.businesses[5].business-name}?useUnicode=true&characterEncoding=utf-8
        user: ${base.db.user}
        password: ${base.db.password}
      provider:
        module-name: ${base.group.suffix}-${micro-services-module-generator-properties.businesses[5].business-name}-provider
        service-implements-package-name: com.${base.group.suffix}.service
        service-implements-save-path: ${base.path.root-path}\${base.group.suffix}-${micro-services-module-generator-properties.businesses[5].business-name}-provider\src\main\java\${base.group.prefix}\${base.group.suffix}\service






